### ISSUE TITLE
NetworkAllowedClientHosts option is excluding all other servers from responding

### ISSUE THREAD

**Issue by snakeb1t** [choria-io/go-network-broker#67]
While testing the `NetworkAllowedClientHosts` option, I found that node discovery was only returning the nodes listed in the option, where it should have returned all the other servers.

Traced it back to this error message: `NATS client on broker_host encountered an error: nats: Permissions Violation for Publish to \"mcollective.reply.fqdn.bc1d24...\"`

Seems that default publish perms are too strict when `NetworkAllowedClientHosts` option is enabled.

**Comment by ripienaar** [comment]
thank you
